# site settings
title: Little Spoon Creative
subtitle: by HTML5 UP
email: info@littlespoon.co.nz
description: Little Spoon offer a range of Graphic Design and Copywriting Solutions To Fit Your Brand and Budget. Contact Us For a Quote Today!
baseurl: "/home" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 35 Marino Street
city: Ohakune
state: Ruapehu
zip_code: 4691
country: New Zealand
phone: 021 083 08457

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/littlespooncreative/
googleplus_url: 
instagram_url: https://www.instagram.com/littlespooncreative/
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
